apiVersion: console.openshift.io/v1
kind: ConsoleYAMLSample
metadata:
  name: secrets-store-csi-secretproviderclass-azure
spec:
  targetResource:
    apiVersion: secrets-store.csi.x-k8s.io/v1
    kind: SecretProviderClass
  title: Example SecretProviderClass - Azure Key Vault
  description: |
    An example SecretProviderClass for Azure Key Vault
  yaml: |
    apiVersion: secrets-store.csi.x-k8s.io/v1
    kind: SecretProviderClass
    metadata:
      name: NAME
      namespace: NAMESPACE
    spec:
      provider: azure
      parameters:
        clientID: "CLIENT_ID"
        keyvaultName: "KEY_VAULT_NAME"
        tenantId: "TENANT_ID"
        objects: |
          array:
            - |
              objectName: SECRET_NAME
              objectType: secret
              objectVersion: ""
