apiVersion: console.openshift.io/v1
kind: ConsoleYAMLSample
metadata:
  name: secrets-store-csi-secretproviderclass-sample
spec:
  targetResource:
    apiVersion: secrets-store.csi.x-k8s.io/v1
    kind: SecretProviderClass
  title: Example SecretProviderClass - HashiCorp Vault
  description: |
    An example SecretProviderClass for HashiCorp Vault
  yaml: |
    apiVersion: secrets-store.csi.x-k8s.io/v1
    kind: SecretProviderClass
    metadata:
      name: NAME
      namespace: NAMESPACE
    spec:
      provider: vault
      parameters:
        vaultAddress: "http://VAULT_IP_ADDRESS:8200"
        roleName: VAULT_ROLE
        objects: |
          - objectName: NAME_FOR_MOUNTED_FILE_CONTAINING_SECRET
            secretPath: SECRET_PATH_IN_VAULT
            secretKey: SECRET_KEY_NAME_IN_VAULT
